### ISSUE TITLE
Task bar notifications

### ISSUE THREAD

**Issue by JMLX42** [thecoderok/vsdingextension#1]
Hello,

could it be possible to have a notification in the Windows task bar instead?

Sound might be great, but I usually code with music and I simply won't hear them.
Plus notifications stick when sounds just play once...

Doable?

Regards,

**Comment by thecoderok** [comment]
Looking at it.

**Comment by thecoderok** [comment]
Resolved with checkin f18fcd2a14f0e680daf790e49d33479a5ef6dd39
