### ISSUE TITLE
Can't install your extension in new VS"15"Preview

### ISSUE THREAD

**Issue by jakubsuchybio** [thecoderok/vsdingextension#11]
Hi,
### Installed product versions
- Visual Studio: [15 Preview]
### Description

At build 2016 Microsoft released Visual Studio 15 Preview.
There are some extensions that work there, but some that are not even searchable in "Extensions and Updates". Yours is one of those that are not searchable and not installable.
### Steps to recreate
1. Install Visual Studio 15 Preview: https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx (Visual Studio "15" Preview with new installer)
2. Open VS15Preview
3. Open Extensions and Updates
4. Click on Online in the menu
5. Search for Visual Studio Ding
6. Your extension doesn't pop up
### Current behavior

Your extension is not searchable in new Visual Studio 15 Preview
### Expected behavior

Your extension should or could be also in VS15Preview :)
### Steps to fix

As I am writing this, one of other extension makers already fixed this issue for his extension here:
https://github.com/cpmcgrath/codealignment/issues/43

You only need to add these:

``` xml
<VisualStudio Version="15.0">
    <Edition>Pro</Edition>
    <Edition>Community</Edition>
</VisualStudio>
```

into your `.vsixmanifest` file into section `<SupportedProducts>` and it should work. :)

Regards.

**Comment by thecoderok** [comment]
Hi, thank you for reporting the issue.
Can you please retry searching it? should be available now.

**Comment by jakubsuchybio** [comment]
Still nothing. If those brackets work like mathematical arrays, then maybe try changing the right one ')' with ']'.

**Comment by thecoderok** [comment]
Hi, can you please check now? I could not be propagated to the search engine at that time.

thank you!

**Comment by jakubsuchybio** [comment]
Still couldn't be found.
![image](https://cloud.githubusercontent.com/assets/6567287/14835171/bcf7cc46-0c08-11e6-87eb-cd54f1301cec.png)

**Comment by thecoderok** [comment]
Strange. Gallery says that those are supported versions (what is your VS version btw?):
Supported versions:
Visual Studio 2015
Visual Studio 2013
Supported Visual Studio 2013 Editions:
Visual Studio 2013 Professional
Visual Studio 2013 Premium
Visual Studio 2013 Ultimate
Supported Visual Studio 2015 Editions:
Visual Studio 2015 Community
Visual Studio 2015 Professional
Visual Studio 2015 Enterprise

**Comment by jakubsuchybio** [comment]
Visual Studio 15 Preview is new version. Old Visual Studio 2015 is version 14.0, new Visual Studio 15 Preview is version 15.0, so you should include the 15.0.
![image](https://cloud.githubusercontent.com/assets/6567287/14835758/c6db0a9a-0c0b-11e6-96c5-6e8acf89e03a.png)

**Comment by thecoderok** [comment]
sorry, could you please try now?

Supported versions:
Visual Studio 15
Visual Studio 2015
Visual Studio 2013
Supported Visual Studio 2013 Editions:
Visual Studio 2013 Professional
Visual Studio 2013 Premium
Visual Studio 2013 Ultimate
Supported Visual Studio 2015 Editions:
Visual Studio 2015 Community
Visual Studio 2015 Professional
Visual Studio 2015 Enterprise
Supported Visual Studio 15 Editions:
Visual Studio 15 Community
Visual Studio 15 Professional
Visual Studio 15 Enterprise

**Comment by jakubsuchybio** [comment]
Sure. It works now. Thanks!

**Comment by thecoderok** [comment]
thank you for helping me to figure that out!
