### ISSUE TITLE
Extension not loading in VS2012 Premium

### ISSUE THREAD

**Issue by groma84** [thecoderok/vsdingextension#4]
The extension is not loading correctly in VS2012 Premium.

The error message in ActivityLog.xml is:

```
<entry>
    <record>699</record>
    <time>2015/06/22 07:27:48.839</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [VsDingExtensionProjectPackage]</description>
    <guid>{26BA08D0-0D25-4479-8684-3054DD122876}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Die Datei oder Assembly "Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.</errorinfo>
  </entry>
```

It does not find "Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

I tried to open the source code of the extension to have a look at the dependencies there but I can't open it because it has been created with a newer, incompatible(?) version of Visual Studio.

I never tried older version of the Ding extension so I don't know if the error is related to the VS2015 support or something like that.

**Comment by thecoderok** [comment]
Looking into the issue

**Comment by thecoderok** [comment]
fixed,
