### ISSUE TITLE
Custom sound for ding

### ISSUE THREAD

**Issue by jakubsuchybio** [thecoderok/vsdingextension#5]
Hi,
I read your answer on vsgallery Q and A: https://visualstudiogallery.msdn.microsoft.com/941d0ed0-1218-452e-8585-d3ac693cda17 about creating custom sound for dings.
I just wanted to ask if you have some timeline for this feature.
Thanks.
Regards Jacob

**Comment by thecoderok** [comment]
Added in version 1.8. Please update.
