### ISSUE TITLE
VS 2015 stops working when looking at Test Manager Window

### ISSUE THREAD

**Issue by dparvin** [thecoderok/vsdingextension#8]
When I have a bunch of unit tests and Coded UI Tests in different projects (I don't know that the number or types matter) when I switch to the Test Manager window, VS tries to load information into the page and stops working.  I end up with a file like the one I attached here in my temp folder.  I went and did a repair on my VS 2015 Update 1 install and it did not effect anything, it still stops.  Uninstalled the vs ding extension and now I can work with my tests.  I went and looked at the folder where vs ding is installed and I found that you were shipping some files that might be causing the issue.  It looks like you have Microsoft.VisualStudio.TestWindow.Core.dll and Microsoft.VisualStudio.TestWindow.Interfaces.dll in the folder and they are VS 2013 files not vs 2015 files.  When vs 2015 tries to use them it has issues.

[MSBuild_5b340c84-4537-4853-b4b6-3740450bd7f7.failure.txt](https://github.com/thecoderok/vsdingextension/files/81962/MSBuild_5b340c84-4537-4853-b4b6-3740450bd7f7.failure.txt)

**Comment by thecoderok** [comment]
thank you for reporting it. Will take a look

**Comment by thecoderok** [comment]
I can repro the issue as well

**Comment by thecoderok** [comment]
fixed

**Comment by dparvin** [comment]
Thanks for the quick turn around.  :)
